### ISSUE TITLE
cross-pi-msgpack-c.sh  runing fail

### ISSUE THREAD

**Issue by liuqimintb** [arnholm/cross-pi#1]
Cloning into 'msgpack-c'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 24233 (delta 6), reused 8 (delta 2), pack-reused 24209
Receiving objects: 100% (24233/24233), 13.32 MiB | 33.00 KiB/s, done.
Resolving deltas: 100% (16262/16262), done.
CMake Error: The source directory "/tmp/build_msgpack-c/msgpack-c" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No rule to make target 'install'.  Stop.
Error: /home/liuqimin/cross-pi-build/libraries/msgpack-c not found. Build failed

**Comment by arnholm** [comment]
Thanks. msgpack-c now requires 'cpp_master' branch to be used instead of 'master'. The script has been updated to do that. Please pull the update, run and report back.

**Comment by liuqimintb** [comment]
Hi
  useing the new script,but get the new error:

Cloning into 'msgpack-c'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 24233 (delta 6), reused 8 (delta 2), pack-reused 24209
Receiving objects: 100% (24233/24233), 13.32 MiB | 19.00 KiB/s, done.
Resolving deltas: 100% (16262/16262), done.
Branch 'cpp_master' set up to track remote branch 'cpp_master' from 'origin'.
Switched to a new branch 'cpp_master'
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /home/liuqimin/cross-pi-build/buildroot/output/host/bin/arm-linux-g++
-- Check for working CXX compiler: /home/liuqimin/cross-pi-build/buildroot/output/host/bin/arm-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR chrono system timer)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  CMakeLists.txt:86 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/build_msgpack-c/msgpack-c/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'install'.  Stop.
Error: /home/liuqimin/cross-pi-build/libraries/msgpack-c not found. Build failed

**Comment by arnholm** [comment]
Ok, The problem is that msgpack-c is now using BOOST. I have added BOOST_ROOT to the script, it means you must run cross-pi-boost.sh before running cross-pi-msgpack-c.sh
I tested this on my machine and it works now. Please pull again.

**Comment by liuqimintb** [comment]
It's work now! thanks.
